#! /bin/bash
set -e 

if test `hostname` = "iamm44p"; then
  PYTHON_INCLUDE_PATH=~/pool/include/python2.3
  BOOST_PATH=$HOME/local/work/boost
else
  BOOST_PATH=$HOME/work/boost
  PYTHON_INCLUDE_PATH=/usr/include/python2.3
fi

function run()
{
  echo "$@"
  "$@"
}

run c++ -g -fPIC -ftemplate-depth-256\
  -I$BOOST_PATH -I$PYTHON_INCLUDE_PATH \
  -c pyangle.cpp -o pyangle.o
run cc -fPIC -DEXTERNAL_TEST -DLINUX -DTRILIBRARY -c triangle.c -o triangle.o
run c++ -shared pyangle.o triangle.o -L$BOOST_PATH -lboost_python -o pyanglemetalmodule.so 
