#! /bin/bash
set -e 

BOOST_PATH=$HOME/diplomarbeit/python-packages/boost
PYTHON_INCLUDE_PATH=/usr/include/python2.3

function run()
{
  echo "$@"
  "$@"
}

run c++ -g -fPIC -I$BOOST_PATH -I$PYTHON_INCLUDE_PATH -c pyangle.cpp -o pyangle.o
run cc -fPIC -DEXTERNAL_TEST -DLINUX -DTRILIBRARY -c triangle.c -o triangle.o
run c++ -shared pyangle.o triangle.o -L$BOOST_PATH -lboost_python -o pyanglemetalmodule.so 
