import os

env = Environment(
    ENV = { 
      "PATH" : os.environ["PATH"],
    } )
env.Replace( CPPPATH = [], LIBS = [], LIBPATH = [], CPPDEFINES = [],
    CXXFLAGS = "", CCFLAGS = "" )

env["BOOST_PATH"] = "%s/work/boost" % os.environ["HOME"]
env["PYTHON_INCLUDE_PATH"] = "/usr/include/python2.3"
env["SHLIBPREFIX"] = ""

env.Append( CXXFLAGS = " -fmessage-length=0" )
env.Append( CPPPATH = "$BOOST_PATH" )
env.Append( CPPPATH = "$PYTHON_INCLUDE_PATH" )
env.Append( CPPDEFINES = "EXTERNAL_TEST" )
env.Append( CPPDEFINES = "LINUX" )
env.Append( CPPDEFINES = "TRILIBRARY" )
env.Append( LIBPATH = "$BOOST_PATH" )

env.SharedLibrary( "pyanglemetalmodule", 
    [ "triangle.c", "pyangle.cpp" ], LIBS = "boost_python" )
